services:
  ### Netbox ###
  netbox:
    #image: docker.io/netboxcommunity/netbox:${VERSION-v4.4-3.4.1}
    image: daily12/cyber-automation:latest
    container_name: netbox
    depends_on:
      - postgres
      - redis
      - redis-cache
    env_file: env/netbox.env
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_PASSWORD: MyPassword#123
    user: "unit:root"
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      start_period: 360s
      timeout: 3s
      interval: 15s
    volumes:
      - ./configuration:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
    ports:
      - "9455:8080"
    restart: unless-stopped

  ### NetBox worker ###
  netbox-worker:
    #image: docker.io/netboxcommunity/netbox:${VERSION-v4.4-3.4.1}
    image: daily12/cyber-automation:latest
    container_name: netbox-worker
    depends_on:
      - netbox
    user: "unit:root"
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 25s
      timeout: 3s
      interval: 15s
    volumes:
      - ./configuration:/etc/netbox/config:ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
    restart: unless-stopped

  ### PostgreSQL database ###
  postgres:
    image: docker.io/postgres:17-alpine
    container_name: netbox-postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      start_period: 20s
      timeout: 5s
      interval: 10s
      retries: 5
    env_file: env/postgres.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  ### Redis ###
  redis:
    image: docker.io/valkey/valkey:8.1-alpine
    container_name: netbox-redis
    command: ["sh", "-c", "valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD"]
    healthcheck: &redis-healthcheck
      test: ["CMD-SHELL","[ $$(valkey-cli --pass \"$${REDIS_PASSWORD}\" ping) = 'PONG' ]"]
      timeout: 3s
      interval: 5s
      retries: 5
    env_file: env/redis.env
    volumes:
      - netbox-redis-data:/data
    restart: unless-stopped

  ### Redis cache ###
  redis-cache:
    image: docker.io/valkey/valkey:8.1-alpine
    container_name: netbox-redis-cache
    command: ["sh", "-c", "valkey-server --requirepass $$REDIS_PASSWORD"]
    healthcheck: *redis-healthcheck
    env_file: env/redis-cache.env
    volumes:
      - netbox-redis-cache-data:/data
    restart: unless-stopped


volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-reports-files:
    driver: local
  netbox-scripts-files:
    driver: local
    
